name: Windows 11 ARM
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  python_bindings_windows_11_arm:
    uses: ./.github/workflows/python_bindings_reusable.yaml
    with:
      run_os: windows-11-arm
      run_optional: false
      python_version: "3.11"
